// libs/react/layouts-react/src/lib/header/header.tsx
import { PORTFOLIO_LAYOUT_DEFAULTS, PORTFOLIO_LAYOUT_LABELS } from '@portfolio/shared/config';
import { Link, NavLink } from 'react-router-dom';

import { ThemeToggle } from '../theme-toggle/theme-toggle';
import styles from './header.module.scss';

export type HeaderProps = {
  onMenuOpen?: () => void;
  brandLabel?: string;
  links?: Array<{ name: string; link: string }>;
};

const DEFAULT_LINKS = PORTFOLIO_LAYOUT_DEFAULTS.links;

export function Header({
  onMenuOpen,
  brandLabel = PORTFOLIO_LAYOUT_DEFAULTS.brandLabel,
  links = DEFAULT_LINKS,
}: HeaderProps) {
  return (
    <header className={styles.header}>
      <div className={styles.inner}>
        <Link className={styles.brand} to="/" data-testid="brand">
          {brandLabel}
        </Link>
        <button
          className={styles.menuBtn}
          aria-label={PORTFOLIO_LAYOUT_LABELS.openNavigation}
          type="button"
          onClick={onMenuOpen}
        >
          <span className="material-symbols-outlined" aria-hidden="true">
            menu
          </span>
        </button>

        <nav className={styles.nav}>
          {links.map((link) => (
            <NavLink
              key={link.link}
              to={link.link}
              className={({ isActive }) =>
                `${styles.navLink} ${isActive ? styles.active : ''}`.trim()
              }
            >
              {link.name}
            </NavLink>
          ))}
          <ThemeToggle />
        </nav>
      </div>
    </header>
  );
}

export default Header;

// libs/angular/layouts/src/lib/header.ts
import { Component, input, output } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { PORTFOLIO_LAYOUT_DEFAULTS, PORTFOLIO_LAYOUT_LABELS } from '@portfolio/shared/config';
import { ThemeToggle } from './theme-toggle';

@Component({
  selector: 'lib-portfolio-header',
  imports: [RouterLink, RouterLinkActive, ThemeToggle],
  template: `
    <header class="header">
      <div class="inner">
        <a class="brand" routerLink="/">{{ title() }}</a>
        <button class="menu-btn" [attr.aria-label]="openNavigationLabel" (click)="menuOpen.emit()">
          <span class="material-symbols-outlined" aria-hidden="true">menu</span>
        </button>

        <nav class="nav">
          @for (link of links(); track $index) {
            <a [routerLink]="link.link" routerLinkActive="active">
              {{ link.name }}
            </a>
          }
          @if (themeToggle()) {
            <lib-portfolio-theme-toggle />
          }
        </nav>
      </div>
    </header>
  `,
  styles: [
    `
      .header {
        background-color: var(--color-header-bg);
        border-bottom: 1px solid var(--color-header-border);
        position: sticky;
        top: 0;
        z-index: 50;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      }

      .inner {
        display: flex;
        justify-content: space-between;
        padding: 1rem 1.5rem;
        max-width: 1280px;
        margin: 0 auto;
      }

      @media (min-width: 768px) {
        .inner {
          padding: 1.5rem 2rem;
        }
      }

      .menu-btn {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 2.5rem;
        height: 2.5rem;
        border: 1px solid var(--color-border);
        border-radius: 0.5rem;
        background: var(--color-bg);
        color: var(--color-text);
        cursor: pointer;
        transition: background-color 0.2s;
      }

      .menu-btn:hover {
        background-color: var(--color-bg-secondary);
      }

      @media (min-width: 768px) {
        .menu-btn {
          display: none;
        }
      }

      .brand {
        font-size: 1.25rem;
        font-weight: 700;
        color: var(--color-text);
        transition: color 0.2s;
      }

      .brand:hover {
        color: var(--color-primary);
      }

      .nav {
        display: none;
        gap: 2rem;
        align-items: center;
      }

      @media (min-width: 768px) {
        .nav {
          display: flex;
        }
      }

      .nav a {
        color: var(--color-text-secondary);
        font-weight: 500;
        font-size: 1rem;
        transition: color 0.2s;
        position: relative;
      }

      .nav a:hover {
        color: var(--color-primary);
      }

      .nav a.active {
        color: var(--color-primary);
      }

      .nav a.active::after {
        content: '';
        position: absolute;
        bottom: -0.5rem;
        left: 0;
        right: 0;
        height: 2px;
        background-color: var(--color-primary);
        border-radius: 9999px;
      }
    `,
  ],
})
export class Header {
  title = input<string>(PORTFOLIO_LAYOUT_DEFAULTS.brandLabel);
  links = input<Array<{ name: string; link: string }>>(PORTFOLIO_LAYOUT_DEFAULTS.links);
  themeToggle = input<boolean>(true);
  menuOpen = output<void>();
  protected readonly openNavigationLabel = PORTFOLIO_LAYOUT_LABELS.openNavigation;
}
