// libs/angular/layouts/src/lib/theme-toggle.ts
import { Component, OnInit, output } from '@angular/core';
import { PORTFOLIO_LAYOUT_LABELS } from '@portfolio/shared/config';

@Component({
  selector: 'lib-portfolio-theme-toggle',
  standalone: true,
  template: `
    <button
      class="theme-toggle"
      (click)="toggleTheme()"
      [attr.aria-label]="isDarkMode ? switchToLightModeLabel : switchToDarkModeLabel"
      [attr.title]="isDarkMode ? lightModeTitle : darkModeTitle"
    >
      <span class="icon">
        {{ isDarkMode ? '☀️' : '🌙' }}
      </span>
    </button>
  `,
  styles: [
    `
      .theme-toggle {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 2.5rem;
        height: 2.5rem;
        padding: 0;
        background: none;
        border: 1px solid var(--color-border);
        border-radius: 0.5rem;
        cursor: pointer;
        transition: all 0.2s;
        color: var(--color-text);
      }

      .theme-toggle:hover {
        background-color: var(--color-bg-secondary);
        border-color: var(--color-border-secondary);
      }

      .theme-toggle:active {
        transform: scale(0.95);
      }

      .theme-toggle:focus-visible {
        outline: 2px solid transparent;
        outline-offset: 2px;
        box-shadow:
          0 0 0 3px rgba(var(--color-primary-rgb), 0.2),
          0 0 0 5px var(--color-primary);
      }

      .icon {
        font-size: 1.25rem;
        display: flex;
        align-items: center;
        justify-content: center;
      }
    `,
  ],
})
export class ThemeToggle implements OnInit {
  isDarkMode = false;
  private readonly THEME_KEY = 'theme';
  themeChange = output<'dark' | 'light'>();
  protected readonly switchToLightModeLabel = PORTFOLIO_LAYOUT_LABELS.switchToLightMode;
  protected readonly switchToDarkModeLabel = PORTFOLIO_LAYOUT_LABELS.switchToDarkMode;
  protected readonly lightModeTitle = PORTFOLIO_LAYOUT_LABELS.lightModeTitle;
  protected readonly darkModeTitle = PORTFOLIO_LAYOUT_LABELS.darkModeTitle;

  ngOnInit() {
    this.initializeTheme();
  }

  private initializeTheme() {
    const savedTheme = localStorage.getItem(this.THEME_KEY);

    if (savedTheme) {
      this.isDarkMode = savedTheme === 'dark';
    } else {
      // Check system preference
      this.isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
    }

    this.applyTheme();
  }

  toggleTheme() {
    this.isDarkMode = !this.isDarkMode;
    this.applyTheme();
    localStorage.setItem(this.THEME_KEY, this.isDarkMode ? 'dark' : 'light');
  }

  private applyTheme() {
    const html = document.documentElement;
    if (this.isDarkMode) {
      html.classList.add('dark');
      html.classList.remove('light');
    } else {
      html.classList.add('light');
      html.classList.remove('dark');
    }
    this.themeChange.emit(this.isDarkMode ? 'dark' : 'light');
  }
}

// libs/react/layouts-react/src/lib/theme-toggle/theme-toggle.tsx
import { PORTFOLIO_LAYOUT_LABELS } from '@portfolio/shared/config';
import { useEffect, useState } from 'react';

import styles from './theme-toggle.module.scss';

export type ThemeToggleProps = {
  onThemeChange?: (theme: 'dark' | 'light') => void;
};

export function ThemeToggle({ onThemeChange }: ThemeToggleProps) {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const themeKey = 'theme';

  useEffect(() => {
    const savedTheme = typeof window !== 'undefined' ? window.localStorage.getItem(themeKey) : null;

    if (savedTheme) {
      setIsDarkMode(savedTheme === 'dark');
      return;
    }

    if (typeof window !== 'undefined' && window.matchMedia) {
      setIsDarkMode(window.matchMedia('(prefers-color-scheme: dark)').matches);
    }
  }, []);

  useEffect(() => {
    if (typeof document === 'undefined') return;

    const html = document.documentElement;
    if (isDarkMode) {
      html.classList.add('dark');
      html.classList.remove('light');
    } else {
      html.classList.add('light');
      html.classList.remove('dark');
    }

    if (typeof window !== 'undefined') {
      window.localStorage.setItem(themeKey, isDarkMode ? 'dark' : 'light');
    }

    onThemeChange?.(isDarkMode ? 'dark' : 'light');
  }, [isDarkMode, onThemeChange]);

  return (
    <button
      className={styles.themeToggle}
      type="button"
      onClick={() => setIsDarkMode((prev) => !prev)}
      aria-label={
        isDarkMode
          ? PORTFOLIO_LAYOUT_LABELS.switchToLightMode
          : PORTFOLIO_LAYOUT_LABELS.switchToDarkMode
      }
      title={
        isDarkMode ? PORTFOLIO_LAYOUT_LABELS.lightModeTitle : PORTFOLIO_LAYOUT_LABELS.darkModeTitle
      }
    >
      <span className={styles.icon}>{isDarkMode ? '☀️' : '🌙'}</span>
    </button>
  );
}

export default ThemeToggle;
